name = input("กรอกชื่อ\n")
nickname = input("ชื่อเล่น\n")
age = input("อายุ\n")
id = input("รหัสประจำตัว\n")
study = input("ชั้นปี\n")
height = int(input("ส่วนสูง\n"))
weight = int(input("นํ้าหนัก\n"))
num = height + weight
print ("ประวัติโดยย่อ")
print ("ชื่อ : " + name + " อายุ : " + age)
print ("รหัสประจำตัว : " + id + " ชั้นปีที่ : " + study)
print ("ชื่อเล่น : " + nickname)
print ("ส่วนสูง : " + str(height) + "เซนติเมตร" + "นํ้าหนัก : " + str(weight) + "เซนติเมตร")
print ("ส่วนสูง + นํ้าหนัก = " + str(num))