name = input("กรอกชื่อ\n")
nickname = input("ชื่อเล่น\n")
age = input("อายุ\n")
id = input("รหัสประจำตัว\n")
study = input("ชั้นปี\n")
height = int(input("ส่วนสูง\n"))
weight = int(input("นํ้าหนัก\n"))
num = height + weight
print ("ประวัติโดยย่อ")
print (f'ชื่อ : {name} อายุ : {age} ปี')
print (f'รหัสประจำตัว : {id} ชั้นปี : {study}')
print (f'ชื่อเล่น : {nickname}')
print (f'ส่วนสูง : {height} นํ้าหนัก : {weight}')
print (f'ส่วนสูง + นํ้าหนัก = {num}')