name = input("กรอกชื่อ : ")
nickname = input("ชื่อเล่น : ")
age = input("อายุ : ")
id = input("รหัสประจำตัว : ")
study = input("ชั้นปี : ")
height = int(input("ส่วนสูง : "))
weight = int(input("นํ้าหนัก : "))
num = height + weight
print ("\nประวัติโดยย่อ")
print (f'ชื่อ : {name} อายุ : {age} ปี')
print (f'รหัสประจำตัว : {id} ชั้นปี : {study}')
print (f'ชื่อเล่น : {nickname}')
print (f'ส่วนสูง : {height} นํ้าหนัก : {weight}')
print (f'ส่วนสูง + นํ้าหนัก = {num}')